site_name: CircleX Finance Documentation
site_url: https://docs.circlex.finance/
site_description: Comprehensive documentation for CircleX Finance – a USDC-native platform for tokenized real estate investing with CCTP V2 support and compliance-first architecture.

repo_url: https://github.com/nagatejakachapuram/CircleFinanceX-Docs
repo_name: CircleX Finance Docs on GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting_started/quick_start.md
      - KYC & OnchainID: getting_started/kyc_onchainid.md
      - Wallet Connection: getting_started/wallet_connection.md
  - Core Features:
      - CCTP V2 Bridge: features/cctp_bridge.md
      - Multi-Chain Support: features/multi_chain.md
      - Compliance & Security: features/compliance.md
  - Investment Products:
      - Tokenized Real Estate: real_estate/overview.md
      - Index Funds: investment_products/index_funds.md
      - US Treasuries: investment_products/treasuries.md
  - Portfolio Management:
      - Portfolio Overview: portfolio/overview.md
      - Performance Tracking: portfolio/performance.md
      - Transaction History: portfolio/transactions.md
  - Technical Integration:
      - USDC Integration: usdc/onchain.md
      - API Reference: technical/api_reference.md
      - Smart Contracts: technical/smart_contracts.md
  - Compliance:
      - ERC-3643 Standard: compliance/erc3643.md
      - KYC Requirements: compliance/kyc_requirements.md
      - Audit Reports: compliance/audit_reports.md

plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/circlexfinance
    - icon: fontawesome/brands/github
      link: https://github.com/nagatejakachapuram/Circle-Finance
    - icon: fontawesome/brands/discord
      link: https://discord.gg/circlexfinance
